post:
    resource: "@postBundle/Resources/config/routing.yml"
    prefix:   /

get:
    resource: "@getBundle/Resources/config/routing.yml"
    prefix:   /

cine:
    resource: "@cineBundle/Resources/config/routing.yml"
    prefix:   /
    defaults: { _controller: InfocineBundle:Default:index }
    

